/** A task structure generated by a recipe, contains properties needed for queuing. */
export default class TaskData {
  public taskId: string;
  public title: string;
  public index: number;
  public step: number;
  public depends: string[];
  public dependents: string[];
  public image?: string;
  public tool?: string;
  public workdir?: string;
  public args: string[];
  public env: { [name: string]: string };
  public inputs: string[];
  public outputs: string[];
  public weight: number;

  constructor(id: string, title: string) {
    this.taskId = id;
    this.title = title;
    this.index = 0;
    this.step = 0;
    this.depends = [];
    this.dependents = [];
    this.image = null;
    this.tool = null;
    this.workdir = null;
    this.args = [];
    this.env = {};
    this.inputs = [];
    this.outputs = [];
    this.weight = 1;
  }
}
