apiVersion: v1
kind: Pod
metadata:
  name: director
spec:
  restartPolicy: Never
  containers:
    - name: director
      image: 192.168.99.100:30127/factory.director:v1
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /usr/src/app
          name: src
  volumes:
    - name: src
      hostPath:
        path: /home/talin/Projects/nimble/factory
