apiVersion: v1
kind: Service
metadata:
  labels:
    server: client
  name: client-service
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: http
     nodePort: 31003
  selector:
    app: factory
    server: client
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: factory
    server: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: factory
        server: client
    spec:
      containers:
        - name: nginx # Use a vanilla nginx container image
          image: nginx:1.7.9
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
          - mountPath: /etc/nginx/conf.d # Map in the nginx config file file
            name: client-files
            subPath: nginx
          - mountPath: /usr/share/nginx/html # Map in the built assets
            name: client-files
        - name: client
          image: client:0.0.1
          imagePullPolicy: Never
          volumeMounts:
          - mountPath: /usr/share
            name: client-files
          lifecycle:
            postStart:
              exec:
                command: ["cp", "-R", "/usr/nimble/src/client/.", "/usr/share"]
      volumes:
      - name: client-files
        emptyDir: {}
