apiVersion: v1
kind: Service
metadata:
  name: director
  labels:
    server: director
spec:
  ports:
   - port: 8087
     targetPort: http
  selector:
    server: director
    role: replica
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    server: director
  name: director-replica
spec:
  template:
    metadata:
      labels:
        server: director
        role: replica
    spec:
      containers:
        - name: director
          image: director:0.0.1
          imagePullPolicy: Never
          env:
            - name: DB_NAME
              value: Factory
            - name: JOB_QUEUE_NAME
              value: JobQueue
            - name: TASK_QUEUE_NAME
              value: TaskQueue
            - name: PORT
              value: '80'
            - name: USE_PROXY
              value: true
          ports:
          - containerPort: 80
            name: http
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 5
