apiVersion: v1
kind: Service
metadata:
  labels:
    server: director
  name: director
spec:
  type: NodePort
  ports:
   - port: 8080
     targetPort: websocket
     nodePort: 31002
  selector:
    server: deepstream
    role: replica
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    server: directory
  name: director-replica
spec:
  template:
    metadata:
      labels:
        server: director
        role: replica
    spec:
      containers:
        - name: director
          image: director:0.0.1
          imagePullPolicy: Never
          restartPolicy: OnFailure
          stdin: true
          tty: true
          ports:
          - containerPort: 8087
            name: http
          livenessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 5
